### ISSUE TITLE
The contest site won't run on my machine

### ISSUE THREAD

**Issue by tidwellwk** [dtowell/contest-host#1]
I go through all of the steps to get the site running, but when I go to localhost:8000, I get an error that says "This page isn't working" and "localhost is unable to handle this request"

**To Reproduce**
1. cd into contest-host
2. Ensure that the database is created
3. run the php command from the README file to start the server
4. Navigate to localhost:8000
5. Error appears

**Expected behavior**
We expect to see the contest page

**Comment by dtowell** [comment]
Does the php command produce any output?
