### ISSUE TITLE
Delete button doesn't work in edit_notes.php

### ISSUE THREAD

**Issue by Addisonbean** [dtowell/contest-host#4]
**Description**

Attempting to delete a note via the "Delete" button on `/edit_notes.php` does not delete the note. The note remains on the page even in future visits, and the total number of notes shown at the top of the page remains the same. The note is also still visible on `/view_problems.php`. 

No errors are reported in the server logs when attempting to delete a note.

**To Reproduce**

1. Visit `edit_notes.php` and create a note.
2. Click on the id of the note you created, then click the button labeled "Delete".

**Expected behavior**

The note should no longer be displayed on the page once it reloads from the "Delete" button being clicked. It should also no longer be visible on `/view_problems.php`.

**Context**

 - OS: Ubuntu 19.10
 - Browser: Google Chrome 79.0.3945.130
 - PHP: 7.3.11
 - SQLite3: 3.28.0

**Comment by dtowell** [comment]
fixed as bug #5
