### ISSUE TITLE
Documentation Links

### ISSUE THREAD

**Issue by dukehm** [dtowell/contest-host#7]
**Describe the bug**
The links are giving an invalid argument within the ubuntu terminal and they do not go to desired location.

**To Reproduce**
1. Go to index page.
2. Click on any docs link.
3. See error

**Expected behavior**
It should go to specified documentation page.

**Screenshots**
![Capture](https://user-images.githubusercontent.com/23040262/78310616-14623e80-7514-11ea-97c0-976f94d11d0e.PNG)
![Capture1](https://user-images.githubusercontent.com/23040262/78310618-14fad500-7514-11ea-97a1-d02b922f7ef8.PNG)

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser: Chrome

**Comment by dtowell** [comment]
Right, this are outside the code. You get credit for reporting, but it won't be fixed.
